# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PPlanel Tech - Consultoria Criativa
email: contato@pplanel.com.br
description: > # this means to ignore newlines until "baseurl:"
  A PPlanel Tecnologia é especializada em consultoria criativa, desenvolvimento para websites, e-commerces, aplicativos web/mobile e MVP para startups.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pplanel.com.br" # the base hostname & protocol for your site
github_username:  pplanel

# Build settings
markdown: kramdown
